base:
  filesystem:
    depends: [iana-etc]
  glibc:
    depends: [filesystem, linux-api-headers, tzdata]
  gcc:
    depends: [binutils, glibc, isl, mpc, zlib, zstd]
  bash:
    depends: [glibc, ncurses, readline]
    optdepends: [bash-completion]
  perl:
    depends: [db, gdbm, libxcrypt]
base-development:
  binutils:
    depends: [zlib, zstd]
    checkdepends: [bc]
  libtool:
    makedepends: [help2man]
  gawk:
    depends: [libsigsegv, mpfr, readline]
  autoconf:
    depends: [m4]
  diffutils:
  help2man:
    - todo
  texinfo:
    - todo
  bison:
    - todo
  git:
    - todo
base-dependency:
  iana-etc:
    makedepends: [gawk]
  linux-api-headers:
  tzdata:
  zlib:
  zstd:
    depends: [zlib]
    makedepends: [cmake]
    pip: [ninja]
  bc:
    - todo
  isl:
    depends: [gmp]
  mpc:
    depends: [gmp, mpfr]
  ncurses:
  readline:
    depends: [ncurses]
  bash-completion:
  db:
  gdbm:
    depends: [readline]
  libxcrypt:
  libsigsegv:
  m4:
    depends: [libsigsegv]