base:
  filesystem:
    - iana-etc
  glibc:
    - filesystem
    - linux-api-headers
    - tzdata
  gcc:
    - binutils:
        - zlib
        - zstd:
            - zlib
    - glibc
    - isl:
        - gmp
    - mpc:
        - gmp
        - mpfr:
            - gmp
    - zlib
    - zstd
  bash:
    - glibc
    - ncurses
    - readline:
        - ncurses
    - bash-completion
  perl:
    - db
    - gdbm:
        - readline
    - glibc
    - libxcrypt
  bzip2:
    - glibc
  gzip:
    - glibc
    - less:
        - ncurses
        - pcre2
  xz:
    - po4a:
        - Module::Build: cpan
        - Pod::Parser: cpan
  tar:
    - acl:
        - attr
  grep:
    - pcre2
  gawk:
    - libsigsegv
    - mpfr
    - readline
  file:
    - libseccomp
  gettext:
    - acl
    - libunistring
    - libxml2:
        - icu
base-development:
  libtool:
  texinfo:
    - ncurses
  help2man:
    - Locale::gettext: cpan
  m4:
    - libsigsegv
  bison:
    - m4
  flex:
    - m4
  autoconf:
    - m4
  automake:
  which:
  diffutils:
  git: todo
