base:
  filesystem:
    depends: [iana-etc]
  glibc:
    depends: [filesystem, linux-api-headers, tzdata]
  binutils:
    depends: [glibc, zlib, zstd]
    checkdepends: [bc]
  gcc:
    depends: [isl, mpc]
    makedepends: [binutils]
  bash:
    depends: [glibc, ncurses, readline]
  perl:
    depends: [db, gdbm, libxcrypt]
  bzip2:
    depends: [glibc]
  gawk:
    depends: [glibc, libsigsegv, mpfr, readline]
  openssl:
    cpan: [Pod::Man]
  ca-certificates:
    depends: [p11-kit]
    makedepends: [python]
base-dependency:
  iana-etc:
    makedepends: [gawk]
  linux-api-headers:
  tzdata:
  zlib:
  zstd:
    makedepends: [cmake]
  mpc:
    depends: [mpfr]
  isl:
    depends: [gmp]
  ncurses:
    depends: [glibc]
    makedepends: [autoconf, autoconf-archive]
  readline:
    depends: [glibc, ncurses]
  db:
  gdbm:
    depends: [glibc, readline]
  libxcrypt:
    depends: [glibc]
  libsigsegv:
    depends: [glibc]
  help2man:
    cpan: [Locale::gettext]
  libtasn1:
  libffi:
  bash-completion:
    depends: [bash]
  p11-kit:
    depends: [libffi, libtasn1, systemd]
    makedepends: [bash-completion]
