base:
  filesystem:
    - iana-etc
  glibc:
    - filesystem
    - linux-api-headers
    - tzdata
  gcc:
    - binutils:
        - zlib
        - zstd:
            - zlib
    - glibc
    - isl:
        - gmp
    - mpc:
        - gmp
        - mpfr:
            - gmp
    - zlib
    - zstd
  bash:
    - glibc
    - ncurses
    - readline:
        - ncurses
    - bash-completion
  perl:
    - db
    - gdbm:
        - readline
    - glibc
    - libxcrypt
  bzip2:
    - glibc
  gzip:
    - glibc
    - less:
        - ncurses
        - pcre2
  xz:
    - po4a:
        - Module::Build: cpan
        - Pod::Parser: cpan
  tar:
    - acl:
        - attr
  grep:
    - pcre2
  sed:
    - acl
  gawk:
    - libsigsegv
    - mpfr
    - readline
  file:
    - libseccomp
  findutils:
    - glibc
  gettext:
    - acl
    - libunistring
    - libxml2:
        - icu
  openssl:
  ca-certificates:
    - p11-kit:
        - libffi
        - libtasn1
  shadow:
    - acl
    - attr
    - audit:
        - krb5:
            - e2fsprogs
            - keyutils
        - libcap-ng:
            - swig
    - libxcrypt
    - pam:
        - audit
        - libxcrypt
        - libtirpc:
            - krb5
        - pam-config
  coreutils:
    - acl
    - attr
    - gmp
    - libcap:
        - pam
  curl:
    - brotli
    - ca-certificates
    - krb5
    - libidn2:
        - libunistring
    - nghttp2
    - libpsl:
        - libidn2
        - libxslt:
            - libgcrypt:
                - libgpg-error
            - libxml2
    - libssh2:
        - openssl
  util-linux:
    - bash-completion
    - cryptsetup:
        - argon2
        - device-mapper:
            - libedit
            - thin-provisioning-tools
        - json-c
        - openssl
        - popt
    - file
    - libcap-ng
    - libxcrypt
    - ncurses
    - pam
    - readline
    - systemd
base-development:
  linux-api-headers:
  libtool:
  texinfo:
    - ncurses
  help2man:
    - Locale::gettext: cpan
  m4:
    - libsigsegv
  bison:
    - m4
  flex:
    - m4
  autoconf:
    - m4
  automake:
  which:
  diffutils:
  pkg-config: todo
  git: todo
  llvm-project:
    - libedit
    - libffi
    - libxml2
    - PyYAML: pip
  rust:
    - curl
    - llvm-project
    - libffi
  python: todo
