filesystem:
  - iana-etc
glibc:
  - filesystem
  - linux-api-headers:
      - rsync (make)
  - tzdata
zlib:
  - glibc
  - zlib
bzip2:
  - glibc
gzip:
  - glibc
  - less:
      - ncurses
      - pcre2
lz4:
  - glibc
xz:
  - glibc
zstd:
  - glibc
  - lz4
  - xz
  - zlib
tar:
  - acl:
      - attr
  - glibc
  - texinfo (make)
gcc:
  - binutils:
      - jansson
      - zlib
      - zstd
  - glibc
  - isl:
      - gmp
  - mpc:
      - gmp
      - mpfr:
          - gmp
  - zlib
  - zstd
bash:
  - glibc
  - ncurses
  - readline:
      - ncurses
perl:
  - db
  - gdbm:
      - readline
  - glibc
  - libxcrypt
grep:
  - glibc
  - pcre2
sed:
  - glibc
  - acl
gawk:
  - glibc
  - libsigsegv
  - mpfr
  - readline
file:
  - glibc
  - libseccomp
findutils:
  - glibc
gettext:
  - acl
  - glibc
  - libunistring:
      - texinfo (make)
  - libxml2:
      - icu
openssl:
  - glibc
ca-certificates:
  - p11-kit:
      - libffi
      - libtasn1
  - python (make)
pam:
  - audit:
      - krb5:
          - e2fsprogs
          - keyutils
          - libedit
          - lmdb
          - openldap:
              - cyrus-sasl (make)
      - libcap-ng:
          - swig (make)
      - swig (make)
  - glibc
  - libtirpc:
      - krb5
  - libxcrypt
  - pam-config
shadow:
  - acl
  - attr
  - audit
  - glibc
  - libxcrypt
  - pam
curl:
  - brotli
  - ca-certificates
  - glibc
  - krb5
  - libidn2:
      - libunistring
  - nghttp2
  - libpsl:
      - libidn2
      - libxslt (make)
  - libssh2
  - openldap
  - openssl
python:
  - expat
  - gdbm
  - glibc
  - libffi
  - libnsl:
      - libtirpc
  - libxcrypt
  - sqlite (make)
coreutils:
  - acl
  - attr
  - glibc
  - gmp
  - libcap:
      - pam
  - openssl
util-linux:
  - bash-completion
  - cryptsetup:
      - argon2
      - device-mapper:
          - libaio
          - libedit
          - device-mapper
          - thin-provisioning-tools
          - thin-provisioning-tools (make)
      - json-c
      - popt
  - file
  - glibc
  - libcap-ng
  - libxcrypt
  - ncurses
  - pam
  - readline
  - systemd (make)
iptables:
  - glibc
  - libnetfilter_conntrack:
      - libmnl
      - libnfnetlink
  - libnftnl:
      - libmnl
  - libpcap:
      - dbus:
          - audit
          - expat
      - libnl
systemd:
  - acl
  - audit
  - bzip2
  - cryptsetup
  - dbus
  - elfutils
  - glibc
  - iptables
  - kbd
  - kmod
  - libcap
  - libgcrypt:
      - libgpg-error
  - libidn2
  - libseccomp
  - lz4
  - openssl
  - pam
  - pcre2
  - xz
  - zlib
  - zstd
  - curl (make)
  - kexec-tools (make)
  - gnutls (make)
  - gperf (make)
  - libmicrohttpd (make)
  - libxslt (make)
  - p11-kit (make)
  - quota (make)
  - util-linux (make)
wget2:
  - brotli
  - gnutls:
      - gmp
      - libidn2
      - libtasn1
      - libunistring
      - nettle:
          - gmp
      - p11-kit
  - gpgme:
      - gnupg:
          - gnutls
          - libassuan:
              - libgpg-error
          - libgcrypt
          - libgpg-error
          - libksba:
              - libgpg-error
          - npth
          - openldap
          - pinentry:
              - libassuan
              - libcap
          - sqlite:
              - tcl (make)
      - libassuan
      - libgpg-error
      - swig (make)
  - libidn2
  - libmicrohttpd:
      - gnutls
  - libpsl
  - lzip
  - nghttp2
  - pcre2
sudo:
  - glibc
  - libgcrypt
  - openldap
  - pam
pacman:
  - curl
  - fakeroot
  - glibc
  - gpgme
  - libarchive:
      - acl
      - expat
      - lz4
      - nettle
  - libseccomp
procps-ng:
  - glibc
  - ncurses
  - systemd (make)
psmisc:
  - glibc
  - ncurses
iputils:
  - glibc
  - libcap
  - libidn2
  - systemd (make)
iproute2:
  - db
  - elfutils
  - glibc
  - iptables
  - libcap
  - libtirpc
  - libmnl
pciutils:
  - glibc
  - hwdata
  - kmod
usbutils:
  - glibc
  - hwdata
  - libusb
  - systemd (make)
